### ISSUE TITLE
2.4.10 Tail Recursion example needs package `zarith`

### ISSUE THREAD

**Issue by eeff** [cs3110/textbook#86]
*Section 2.4.10*, the `zfact_tr` example needs package `zarith` installed, but the installation instruction in *Installing OCaml* chapter does not include it.

Observed:
```
utop # #require "zarith.top"
No such package: zarith.top
```

**Comment by clarksmr** [comment]
Thanks so much! I really appreciate the PR, but in this case, I would prefer a different solution. 

For now, I'd like to avoid adding Zarith to the install packages. That's because it relies on GMP, which needs to be installed by the user (or by OPAM if it can). That would be committing me to unnecessary tech support with my students at Cornell (if they can't get it installed).

So since Zarith is currently used in the textbook for just this one throw-away example, I'll resolve the issue by telling the reader to install it *if* they want to follow along with the code.  Done in 28ecae7.

**Comment by eeff** [comment]
Thanks for the solution. It's a very good book, and thanks very much for the videos. Best regards.
